### ISSUE TITLE
Probléma: kifogásolhatóságok a dokumentációban

### ISSUE THREAD

**Issue by 1082008** [Decesso/sdl-tetris#73]
A használati esetek leírása sokkal jobb lett a korábbi változathoz képest. Sajnos nem látom kiemelve a különbségeket, csak a mostani verziót, viszont ezzel kapcsolatban találtam javításra érdemes dolgokat, ezeket részletezném alább.

Helytelenül írt szavak (elgépelések is):

- lejebb
- eltűntetésénél
- tellik
- Python2-őt
- architectúrát
- nyílvánul
- Interface (interfész)
- Iránytásért
- meglelelő
- leaállítása
- kliens-ben (kliensben)
- kliens-nek (kliensnek)
- helyezete
- eltűntetésekor
- felsó
- aott
- funckionalitások
- maxálisan
- hoszabb
- felhasználásval
- szervíz
- nyílvántartásába
- legfrisebb

http://helyesiras.mta.hu/

Nehogy helyesírás ellenőrzés nélkül add be, az nem lenne méltó egy szakdolgozathoz! Vannak olyan mondatok, amelyek végén nincs írásjel.

Én a "mana" szó helyett kerestem volna egy magyar megfelelőt. (Pontszám?)

A Game Loop néha game loop, néha gameloop. Válaszd ki az egyiket, és használd mindenütt azt, legyél konzekvens.

A nagy szekvenciadiagramok már elég apróbetűsek, nyomtatásban nem lesz könnyű dolga minden olvasónak. Ráadásul szerintem a három nagy szekvenciadiagram eléggé hasonlít egymásra. Lehet, hogy elég lenne azt a részét szerepeltetni az ábrának, ami valóban lényeges.

Az osztálynév hivatkozásokat jó lenne alternatív módon megjeleníteni a szövegben.

Vannak stilisztikailag erősen kifogásolható mondatok. Pl.

`Amennyiben a játékszerver azt észlelte, hogy becsatlakozott mindkét játékos, kiküld mindkét kliens-nek egy start üzenetet ami mindkét kliensben azt váltja ki, hogy elkezdik az inicializációt.`

Még egyszerűbb is lehetne:

`A játékszerver a két játékos beérkezése esetén mindkettejüknek start üzenetet küld, ami a felekben az "inicializáció" műveletet váltja ki.`

Aztán:

`Az alábbi ábra mutatja a játék fejében létrejövő objektumhívásokat [...]`

Mi a "játék feje"? Ilyen nincs, ha egymás közt beszélünk, akkor megértem, de egy szakdolgozatban ilyen szlengnek nincs keresnivalója. Mi az az "objektumhívás"? Objektumok közti függvényhívásokra gondolsz?

Az UML diagramokon semmi keresnivalója az unique_ptr és shared_ptr template-eknek. (Teljesen feleslegesen veszi el a hangsúlyt arról, hogy hivatkozás átadása történik.) A statikus osztálydiagramok magas szinten modellezik a felépítést, ezen a szinten kompozíciót és asszociációt kellett volna használni. Furcsa is, hogy pl. a GameLoop osztály önmagában áll, és a kapcsolatok feltérképezéséhez bele kell olvasni az adatmezőkbe, nem pedig kapcsolódó dobozok vannak az ábrán.

Mi az az enumerátor? Felsorolt típus?

`a kapott ip-port pároshoz csatlakozik` &rarr; `a megadott TCP portra csatlakozik` - elég furcsán hangzik ez a "pároshoz csatlakozás".

`amennyiben a kapcsolat nem sikerül exception-el kiszáll` &rarr; `a kapcsolatfelépítés sikertelensége esetén kivételt dob` - ez a "kiszáll" is elég pongyola, és a kivételt érdemes lefordítani, de ha valamiért mégis meghagynád, akkor legalább ragozd megfelelően: `exception`-nel.

Lehet, hogy csak nálam jelenik meg pixelesen, de szerintem nem érdemes pixelgrafikus ábrákat szerepeltetni. A vektorgrafika _sokkal_ jobban néz ki.

A függvény helyett ne használd a funkció szót, nem ugyanazt jelenti.

A `LogicInterface` osztálydiagramján rengeteg tagfüggvény szerepel. Nagyon gyanús, hogy sérül az SRP. Ugyanezt látom a `Logic` osztály esetében is.

A "3.1. Fejlesztőeszközök" című szakaszban megmagyarázatlanul merül fel az issue, a milestone és a sprint fogalma. A "megejthető" szót mellőzném, szintén stilisztikai okból. A menedzselés helyett próbáljunk magyar szót találni. A build process is szépen lefordítható fordítási folyamatként. A szerviz egyrészt rövid i, másrészt magyarul szolgáltatás az a szó, amit szerettél volna lefordítani. A GitHub nem verziókezelő, a Git az. Mi az a yamel fájl?! YML fájlra gondoltál? Nem a C++14 a nyelv legfrissebb verziója. Az SDL nem réteget nyújt, hanem absztrakciós réteget.

A C++ Core Guidelines ne "a kódoláskor" legyen irányadó, hanem kódoláskor. Indentálás helyett talán érdemes a behúzás szót használni. Egyébként a C++ Core Guidelines-ból milyen szabályokat követtél? Jó lenne mutatni néhány példát. A kódolási szabályokból is jó lenne a releváns elemekre korlátozni a leírást, mert szerintem nem vág a témába.

A C++ Core Guidelines kettes számú hivatkozásként szerepel, viszont a mű végén Robert C. Martin Clean Code műve jelenik meg az irodalomjegyzékben. Az irodalomjegyzék egyébként feltűnően rövid.

**Comment by 1082008** [comment]
A kódolási szabályainkat esetleg függelékként lehetne szerepeltetni, de abban az esetben át kellene fogalmazni benne a stilisztikailag egy szakdolgozatba nem illeszkedő szerkezeteket.

**Comment by DaweMolnar** [comment]
Nagy részét javítom, de így elsőre van pár dolog ami szerintem nem kerül javításra - 
* A  mana szerepjátékos körben magyarul is mana, így a mana gyakorlatilag már a magyar megfelelő
* Az ábrából kiveszem akkor a shared/unique ptr mutatását, és lecserélem * -ra, viszont az osztályok közti kapcsolatot előtte modelleztem már, ott a GameLoop-hoz vezetnek nyilak, hogy miket használ fel, az a rész amiről beszélsz, az az osztályok részletes kifejtése rész, nem kapcsolatokat modellezek, hanem működést magyarázok.
* Az ábrák minőségét a libreoffice rontja, nem az, hogy milyen formátumban mentettem el, próbálok javítani rajta ahogy lehet
* A C++17 a dokumentáció írásának  idejében még draft volt, ezért nem számított az a legfrisebb verziónak, csak most decemberben lett release-elve.
* Mivel nem használtam irodalmat se a fejlesztéshez, se a dokumentációhoz, ezért az ottani két irodalom is elég force-olt, hogy végre szerepeljen ott valami.

**Comment by DaweMolnar** [comment]
Egyébként, hogy határidőre be tudjam adni holnap vinni kell már nyomtatni, szóval sajnos nagyobb dolgokat már nem tudok javítani benne, viszont a beadáshoz kéne a véleményed róla:

> III. A hallgató szakdolgozatát a témavezető és az esetleges külső konzulens is
> véleményezi. A szakdolgozatok bírálata egy szempontrendszer alapján történik. A
> vélemény a következő értékelési szempontok alapján készül:
> 1. A megoldott feladat programozási nehézsége. Mivel a módszer, az algoritmus előre
> adott, ezeknek a nehézsége, bonyolultsága az értékelésbe nem számítható bele.
> 2. A program minőségi jellemzői: áttekinthetőség, módosíthatóság, kiterjeszthetőség,
> a felhasználóhoz való alkalmazkodás, megbízhatóság, stb.
> 3. A Felhasználói dokumentáció használhatósága, milyen könnyen és gyorsan igazítja
> el a felhasználót a program használatában.
> 4. A Fejlesztői dokumentáció milyen mértékben segíti elő a programban való
> tájékozódást, a program továbbfejlesztését, karbantartását.
> A vizsgált szempontok a következők:
> - a dokumentáció felépítése, nyelvezete, külalakja
> - a program szövegének áttekinthetősége,
> - a dokumentáció részeinek kapcsolata, összhangja (algoritmusok, modulok,
> programszerkezetek),
> - a tesztelés minőségi értékelése.
> 5. A hallgató munkájáról kialakult vélemény.

**Comment by 1082008** [comment]
> A mana szerepjátékos körben magyarul is mana, így a mana gyakorlatilag már a magyar megfelelő

Az olvasói kör mennyire járatos a szerepjátékok világában? Én attól félek, hogy ez a szó önmagában komolytalanná teszi a dolgozatot. (https://youtu.be/8N_tupPBtWQ) A "magyar a megfelelő" esetén szintén hivatkoznod kéne. Sajnos pont az ellenkezőjét tudom igazolni:

http://helyesiras.mta.hu/helyesiras/default/suggest?q=mana
http://idegen-szavak.hu/keres/mana

> Az ábrából kiveszem akkor a shared/unique ptr mutatását, és lecserélem * -ra, viszont az osztályok közti kapcsolatot előtte modelleztem már, ott a GameLoop-hoz vezetnek nyilak, hogy miket használ fel, az a rész amiről beszélsz, az az osztályok részletes kifejtése rész, nem kapcsolatokat modellezek, hanem működést magyarázok.

A működés megértéséhez muszáj látni a kapcsolatokat. A kapcsolódó osztályokat én egy-egy üres téglalappal ugyan, de szerepeltetném.

> A C++17 a dokumentáció írásának idejében még draft volt, ezért nem számított az a legfrisebb verziónak, csak most decemberben lett release-elve.

Ha ezt már most tudod, akkor korrigáld.

> Mivel nem használtam irodalmat se a fejlesztéshez, se a dokumentációhoz, ezért az ottani két irodalom is elég force-olt, hogy végre szerepeljen ott valami.

A Core Guidelines-t azért pótold, mert azt használtad menetközben, de a bibliográfiából mégis hiányzik. A bibliográfiát egyébként ugye generálod?!

Javasolnám még ide, hogy ha esetleg használsz design pattern-t, akkor hivatkozd meg a Gamma-könyvet is. Ezen felül web hivatkozások is szerepelhetnek. Nyilván nem nulláról egyedül te találtál ki mindent. Pl. megemlíthetnéd az alapul vett Tetris játékot is.

**Comment by 1082008** [comment]
> viszont a beadáshoz kéne a véleményed

Ezt mikorra kéne megírnom?

**Comment by DaweMolnar** [comment]
A bekötött szakdolgozattal együtt kell beadni, kötésre kedden adom le, és szerdán vagy csütörtökön elkészül, legkésőbb csütörtökre kéne.

**Comment by 1082008** [comment]
OK, csütörtökre mindenképp meglesz.

**Comment by DaweMolnar** [comment]
Kész, problémák javítva, hozzáraktam egy részt a könyvtárstruktúráról a végéhez, plusz lecseréltem az avatar képeket a képernyőképeken, mert azok jogvédettek voltak, az új képeket egy forrás feltűntetése nélkül is használható stack oldalról szedtem. Plusz sikerült feltennem helyesírásellenőrzőt, szóval minden hiba javítva benne amiről az szólt

**Comment by DaweMolnar** [comment]
Holnap viszem leadni kötésre miután átvettem a tanártól az eredeti témabejelentőt, hogy azzal tudjam beköttetni, 1-2 nap alatt kötik be
